### ISSUE TITLE
Incorrect config separation on export

### ISSUE THREAD

**Issue by Cenness** [peter-evans/kdef#518]
### Describe the bug

Kdef export is very greedy, i.e config that was defined at cluster wide level is propagated as deep as possible.  
Topic exports include default config values.

### Reproduction steps

1. Spin up kafka cluster from kdef tutorial - docs/docs/getting-started.md
2. Run `kdef export broker`:
<details>
<summary>output</summary>

```
Fetching remote per-broker configuration...
Exporting 2 broker definition(s)...
---
apiVersion: v1
kind: broker
metadata:
  name: "1"
spec:
  configs:
    advertised.listeners: INTER://broker1:9092,HOST://localhost:19092
    background.threads: "10"
    compression.type: producer
    listener.security.protocol.map: INTER:PLAINTEXT,HOST:PLAINTEXT
    listeners: INTER://broker1:9092,HOST://broker1:19092
    log.cleaner.backoff.ms: "15000"
    log.cleaner.dedupe.buffer.size: "134217728"
    log.cleaner.delete.retention.ms: "86400000"
    log.cleaner.io.buffer.load.factor: "0.9"
    log.cleaner.io.buffer.size: "524288"
    log.cleaner.io.max.bytes.per.second: "1.7976931348623157E308"
    log.cleaner.max.compaction.lag.ms: "9223372036854775807"
    log.cleaner.min.cleanable.ratio: "0.5"
    log.cleaner.min.compaction.lag.ms: "0"
    log.cleaner.threads: "1"
    log.cleanup.policy: delete
    log.flush.interval.messages: "9223372036854775807"
    log.flush.interval.ms: null
    log.index.interval.bytes: "4096"
    log.index.size.max.bytes: "10485760"
    log.message.downconversion.enable: "true"
    log.message.timestamp.difference.max.ms: "9223372036854775807"
    log.message.timestamp.type: CreateTime
    log.preallocate: "false"
    log.retention.bytes: "-1"
    log.retention.ms: null
    log.roll.jitter.ms: null
    log.roll.ms: null
    log.segment.bytes: "1073741824"
    log.segment.delete.delay.ms: "60000"
    max.connection.creation.rate: "2147483647"
    max.connections: "2147483647"
    max.connections.per.ip: "2147483647"
    max.connections.per.ip.overrides: ""
    message.max.bytes: "1048588"
    metric.reporters: ""
    min.insync.replicas: "1"
    num.io.threads: "8"
    num.network.threads: "3"
    num.recovery.threads.per.data.dir: "1"
    num.replica.fetchers: "1"
    principal.builder.class: org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder
    sasl.enabled.mechanisms: GSSAPI
    sasl.kerberos.kinit.cmd: /usr/bin/kinit
    sasl.kerberos.min.time.before.relogin: "60000"
    sasl.kerberos.principal.to.local.rules: DEFAULT
    sasl.kerberos.service.name: null
    sasl.kerberos.ticket.renew.jitter: "0.05"
    sasl.kerberos.ticket.renew.window.factor: "0.8"
    sasl.login.refresh.buffer.seconds: "300"
    sasl.login.refresh.min.period.seconds: "60"
    sasl.login.refresh.window.factor: "0.8"
    sasl.login.refresh.window.jitter: "0.05"
    sasl.mechanism.inter.broker.protocol: GSSAPI
    ssl.cipher.suites: ""
    ssl.client.auth: none
    ssl.enabled.protocols: TLSv1.2,TLSv1.3
    ssl.endpoint.identification.algorithm: https
    ssl.engine.factory.class: null
    ssl.keymanager.algorithm: SunX509
    ssl.keystore.location: null
    ssl.keystore.type: JKS
    ssl.protocol: TLSv1.3
    ssl.provider: null
    ssl.secure.random.implementation: null
    ssl.trustmanager.algorithm: PKIX
    ssl.truststore.location: null
    ssl.truststore.type: JKS
    unclean.leader.election.enable: "false"
  deleteUndefinedConfigs: false
---
apiVersion: v1
kind: broker
metadata:
  name: "2"
spec:
  configs:
    advertised.listeners: INTER://broker2:9092,HOST://localhost:19093
    background.threads: "10"
    compression.type: producer
    listener.security.protocol.map: INTER:PLAINTEXT,HOST:PLAINTEXT
    listeners: INTER://broker2:9092,HOST://broker2:19093
    log.cleaner.backoff.ms: "15000"
    log.cleaner.dedupe.buffer.size: "134217728"
    log.cleaner.delete.retention.ms: "86400000"
    log.cleaner.io.buffer.load.factor: "0.9"
    log.cleaner.io.buffer.size: "524288"
    log.cleaner.io.max.bytes.per.second: "1.7976931348623157E308"
    log.cleaner.max.compaction.lag.ms: "9223372036854775807"
    log.cleaner.min.cleanable.ratio: "0.5"
    log.cleaner.min.compaction.lag.ms: "0"
    log.cleaner.threads: "1"
    log.cleanup.policy: delete
    log.flush.interval.messages: "9223372036854775807"
    log.flush.interval.ms: null
    log.index.interval.bytes: "4096"
    log.index.size.max.bytes: "10485760"
    log.message.downconversion.enable: "true"
    log.message.timestamp.difference.max.ms: "9223372036854775807"
    log.message.timestamp.type: CreateTime
    log.preallocate: "false"
    log.retention.bytes: "-1"
    log.retention.ms: null
    log.roll.jitter.ms: null
    log.roll.ms: null
    log.segment.bytes: "1073741824"
    log.segment.delete.delay.ms: "60000"
    max.connection.creation.rate: "2147483647"
    max.connections: "2147483647"
    max.connections.per.ip: "2147483647"
    max.connections.per.ip.overrides: ""
    message.max.bytes: "1048588"
    metric.reporters: ""
    min.insync.replicas: "1"
    num.io.threads: "8"
    num.network.threads: "3"
    num.recovery.threads.per.data.dir: "1"
    num.replica.fetchers: "1"
    principal.builder.class: org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder
    sasl.enabled.mechanisms: GSSAPI
    sasl.kerberos.kinit.cmd: /usr/bin/kinit
    sasl.kerberos.min.time.before.relogin: "60000"
    sasl.kerberos.principal.to.local.rules: DEFAULT
    sasl.kerberos.service.name: null
    sasl.kerberos.ticket.renew.jitter: "0.05"
    sasl.kerberos.ticket.renew.window.factor: "0.8"
    sasl.login.refresh.buffer.seconds: "300"
    sasl.login.refresh.min.period.seconds: "60"
    sasl.login.refresh.window.factor: "0.8"
    sasl.login.refresh.window.jitter: "0.05"
    sasl.mechanism.inter.broker.protocol: GSSAPI
    ssl.cipher.suites: ""
    ssl.client.auth: none
    ssl.enabled.protocols: TLSv1.2,TLSv1.3
    ssl.endpoint.identification.algorithm: https
    ssl.engine.factory.class: null
    ssl.keymanager.algorithm: SunX509
    ssl.keystore.location: null
    ssl.keystore.type: JKS
    ssl.protocol: TLSv1.3
    ssl.provider: null
    ssl.secure.random.implementation: null
    ssl.trustmanager.algorithm: PKIX
    ssl.truststore.location: null
    ssl.truststore.type: JKS
    unclean.leader.election.enable: "false"
  deleteUndefinedConfigs: false
```
</details>

3. Only two lines are different in that spec blocks - `advertised.listeners` and `listeners`  

4. Run `kdef export brokers`
<details>
<summary>output</summary>

```
Fetching remote cluster-wide broker configuration...
Exporting 1 brokers definition(s)...
---
apiVersion: v1
kind: brokers
metadata:
  name: brokers
spec:
  deleteUndefinedConfigs: false
```
</details>

5. Create topic with `kdef apply definitions/topic/tutorial_topic1.yml`:
<details>
<summary>output</summary>

```
Reading definition(s) from file "definitions/topic/tutorial_topic1.yml"
Fetching remote topic...
Topic "tutorial_topic1" does not exist and will be created
topic definition "tutorial_topic1" diff (local -> remote):
-null
+{
+  "apiVersion": "v1",
+  "kind": "topic",
+  "metadata": {
+    "name": "tutorial_topic1"
+  },
+  "spec": {
+    "configs": {
+      "retention.ms": "86400000"
+    },
+    "deleteUndefinedConfigs": false,
+    "partitions": 3,
+    "replicationFactor": 2,
+    "managedAssignments": {
+      "balance": "new",
+      "selection": "topic-cluster-use"
+    },
+    "maintainLeaders": false
+  },
+  "state": {
+    "assignments": [
+      [
+        1,
+        2
+      ],
+      [
+        2,
+        1
+      ],
+      [
+        1,
+        2
+      ]
+    ]
+  }
+}
Creating topic...
Created topic "tutorial_topic1"
Completed apply for topic definition "tutorial_topic1"
```
</details>

6. Export topics config with `kdef export topic`:
<details>
<summary>output</summary>

```
$ cat definitions/topic/tutorial_topic1.yml
apiVersion: v1
kind: topic
metadata:
  name: tutorial_topic1
spec:
  configs:
    retention.ms: "86400000"
  partitions: 3
  replicationFactor: 2

$ kdef export topic
Fetching remote topics...
Exporting 1 topic definition(s)...
---
apiVersion: v1
kind: topic
metadata:
  name: tutorial_topic1
spec:
  configs:
    cleanup.policy: delete
    compression.type: producer
    delete.retention.ms: "86400000"
    file.delete.delay.ms: "60000"
    flush.messages: "9223372036854775807"
    flush.ms: "9223372036854775807"
    follower.replication.throttled.replicas: ""
    index.interval.bytes: "4096"
    leader.replication.throttled.replicas: ""
    max.compaction.lag.ms: "9223372036854775807"
    max.message.bytes: "1048588"
    message.downconversion.enable: "true"
    message.format.version: 3.0-IV1
    message.timestamp.difference.max.ms: "9223372036854775807"
    message.timestamp.type: CreateTime
    min.cleanable.dirty.ratio: "0.5"
    min.compaction.lag.ms: "0"
    min.insync.replicas: "1"
    preallocate: "false"
    retention.bytes: "-1"
    retention.ms: "86400000"
    segment.bytes: "1073741824"
    segment.index.bytes: "10485760"
    segment.jitter.ms: "0"
    segment.ms: "604800000"
    unclean.leader.election.enable: "false"
  deleteUndefinedConfigs: true
  maintainLeaders: false
  partitions: 3
  replicationFactor: 2
```
</details>

7. There are a lot of cluster defined options there

### Expected behavior

Cluster wide config is visible only in cluster wide export.
Default config aren't shown at all.    

### kdef version

0.5.8

### Additional context

Native kafka tools correctly separate configs, although fail to show defaults:
```
$ kafka-topics --bootstrap-server broker1:9092 --describe --topics-with-overrides
Topic: tutorial_topic1  TopicId: -dX_YBYgSXC3sXT8r3dT0g PartitionCount: 3       ReplicationFactor: 2    Configs: retention.ms=86400000

$ kafka-configs --bootstrap-server broker1:9092 --describe --entity-type topics
Dynamic configs for topic tutorial_topic1 are:
  retention.ms=86400000 sensitive=false synonyms={DYNAMIC_TOPIC_CONFIG:retention.ms=86400000}

$ kafka-configs --bootstrap-server broker1:9092 --describe --entity-type brokers
Dynamic configs for broker 1 are:
Dynamic configs for broker 2 are:
Default configs for brokers in the cluster are:
```
